=== ver0n1kas/test-config/schemas/asg-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "protocol": {
          "type": "string"
        },
        "destination": {
          "type": "string"
        },
        "ports": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "log": {
          "type": "boolean"
        }
      },
      "required": [
        "protocol",
        "destination",
        "ports",
        "description",
        "log"
      ]
    }
  }

=== ver0n1kas/test-config/api-sys-h2o-2-24678-h2o-vmware-com/asg/asg.json
[
    {
                    "protocol": "tcp",
                    "destination": "",
                    "ports": "1234",
                    "description": "Allows access to ProductPal mapping service used to approve products",
                    "log": true

    },

    {
                    "protocol": "tcp",
                    "destination": "",
                    "ports": "",
                    "description": "Allows access to Vault",
                    "log": true
    },
    {
                    "protocol": "tcp",
                    "destination": "",
                    "ports": "",
                    "description": "Allows access to ProductPal db",
                    "log": true
    }

]
